### ISSUE TITLE
[bug] Problem using ApacheTomcatScanner on python3.9 and python3.10

### ISSUE THREAD

**Issue by b33fsup3m3** [p0dalirius/ApacheTomcatScanner#19]
python 3.10 execution:

```
┌──(root㉿d3m0n)-[/home/d3m0n/ApacheTomcatScanner]
└─# python3 ApacheTomcatScanner.py
Traceback (most recent call last):
  File "/home/d3m0n/ApacheTomcatScanner/ApacheTomcatScanner.py", line 8, in <module>
    from apachetomcatscanner.__main__ import main
  File "/home/d3m0n/ApacheTomcatScanner/apachetomcatscanner/__main__.py", line 14, in <module>
    from apachetomcatscanner.utils.scan import scan_worker
  File "/home/d3m0n/ApacheTomcatScanner/apachetomcatscanner/utils/scan.py", line 9, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

python 3.9 execution:

```
┌──(root㉿d3m0n)-[/home/d3m0n/ApacheTomcatScanner]
└─# python3.9 ApacheTomcatScanner.py
Traceback (most recent call last):
  File "/home/d3m0n/ApacheTomcatScanner/ApacheTomcatScanner.py", line 8, in <module>
    from apachetomcatscanner.__main__ import main
  File "/home/d3m0n/ApacheTomcatScanner/apachetomcatscanner/__main__.py", line 11, in <module>
    from apachetomcatscanner.Reporter import Reporter
  File "/home/d3m0n/ApacheTomcatScanner/apachetomcatscanner/Reporter.py", line 10, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
```

**Comment by p0dalirius** [comment]
Yes they can.

## Python 3.10 execution

The error `ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)` is a problem in `urllib3`. Please update your `requests` and `urllib3` packages and try again:

```
python3.9 -m pip install urllib3 requests --upgrade
```

## Python 3.9 execution

Your error `ModuleNotFoundError: No module named 'xlsxwriter'` means that you did not install the requirements of ApacheTomcatScanner. Try:

```
python3.9 -m pip install -r requirements.txt --upgrade
```
