### ISSUE TITLE
[bug] No such file or directory: '/usr/local/lib/python3.11/dist-packages/apachetomcatscanner/data/credentials.json'

### ISSUE THREAD

**Issue by p0dalirius** [p0dalirius/ApacheTomcatScanner#33]
```
 apachetomcatscanner -tf results/subdomains.txt 
Apache Tomcat Scanner v3.6 - by @podalirius_

Traceback (most recent call last):
  File "/usr/local/bin/apachetomcatscanner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/apachetomcatscanner/__main__.py", line 197, in main
    config = Config()
             ^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/apachetomcatscanner/Config.py", line 34, in __init__
    self.__load_default_credentials()
  File "/usr/local/lib/python3.11/dist-packages/apachetomcatscanner/Config.py", line 43, in __load_default_credentials
    f = open(path_to_creds, 'r')
        ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/dist-packages/apachetomcatscanner/data/credentials.json'
```

**Comment by p0dalirius** [comment]
Fixed
