### ISSUE TITLE
[bug] get_servers_from_domain() missing 1 required positional argument: 'auth_key'

### ISSUE THREAD

**Issue by itm4n** [p0dalirius/ApacheTomcatScanner#41]
Hello!

I get the following stack trace when trying to enumerate servers from the Active Directory.

```console
$ ./ApacheTomcatScanner.py -ad '***' -ai '***' -au '***' -ap '***' --list-cves --show-cves-descriptions --servers-only
Apache Tomcat Scanner v3.7 - by @podalirius_

Traceback (most recent call last):
  File "/***/ApacheTomcatScanner/./ApacheTomcatScanner.py", line 11, in <module>
    main()
  File "/***/ApacheTomcatScanner/apachetomcatscanner/__main__.py", line 228, in main
    targets = load_targets(options, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/***/ApacheTomcatScanner/apachetomcatscanner/__main__.py", line 48, in load_targets
    targets += get_servers_from_domain(
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_servers_from_domain() missing 1 required positional argument: 'auth_key'
```

It looks like you updated your `sectools` library, but this change was not reflected in `ApacheTomcatScanner`.

https://github.com/p0dalirius/sectools/blob/bb4c46eef1061f819b2a21b8ae5090accf489320/sectools/windows/ldap.py#L247

```python
def get_servers_from_domain(auth_domain, auth_dc_ip, auth_username, auth_password, auth_hashes, auth_key, use_kerberos=False, kdcHost=None, use_ldaps=False, __print=False):
```

https://github.com/p0dalirius/ApacheTomcatScanner/blob/39e2fe1bd9f3b2f17d15f1f3ddc17b460f106fa3/apachetomcatscanner/__main__.py#L48-L56

I don't know if there are other similar discrepancies though.

**Comment by p0dalirius** [comment]
Hey!

I hope you are well!

Thank you, I'll fix that ASAP.
